apiVersion: 1

datasources:
  - name: task_tracker
    type: postgres
    access: proxy
    url: database:5432
    database: task_tracker
    user: tasktracker
    secureJsonData:
      password: changeme
    jsonData:
      sslmode: disable
      postgresVersion: 1500
      timescaledb: false
    editable: true
